=== DavSladk/School/MUL/slides.dtd
<!ELEMENT slides (slide+)>
<!ELEMENT slide (slideClass|text|button|image|audio|video)*>
<!ELEMENT slideClass (#PCDATA)>

<!ELEMENT text (textClass*,value)>
<!ELEMENT textClass (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT button (buttonClass*,to,value)>
<!ELEMENT buttonClass (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT image (imageClass*,src)>
<!ELEMENT imageClass (#PCDATA)>

<!ELEMENT audio (audioClass*,src,loop?)>
<!ELEMENT audioClass (#PCDATA)>

<!ELEMENT video (videoClass*,src,loop?)>
<!ELEMENT viodeClass (#PCDATA)>

<!ELEMENT src (#PCDATA)>
<!ELEMENT loop EMPTY>

=== DavSladk/School/MUL/slides.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE slides SYSTEM "slides.dtd">

<slides>

<!-- slide 0 - postel -->
<slide>

    <slideClass>slide0</slideClass>

    <button>
        <buttonClass>leftBottom</buttonClass>
        <to>2</to>
        <value>Vstanu.</value>
    </button>

    <button>
        <buttonClass>rightBottom</buttonClass>
        <to>1</to>
        <value>Zůstanu v posteli.</value>
    </button>

    <text>
        <textClass>heading</textClass>
        <value>Je ráno. Další nádherný den plný dobrodružství! Co uděláš jako první?</value>
    </text>

    <audio>
        <audioClass>examle</audioClass>
        <src>snoring.mp3</src>
        <loop/>
    </audio>

    <image>
        <imageClass>imageCenter</imageClass>
        <src>bed.jpg</src>
    </image>

</slide>

<!-- slide 1 - you win -->
<slide>

    <slideClass>slide1</slideClass>

    <image>
        <imageClass>imageCenter</imageClass>
        <src>youwin.png</src>
    </image>

    <audio>
        <audioClass>examle</audioClass>
        <src>fireworks.mp3</src>
        <loop/>
    </audio>

    <button>
        <buttonClass>centerBottom</buttonClass>
        <to>0</to>
        <value>Restart</value>
    </button>

</slide>

<!-- slide 2 - v domě -->
<slide>

    <slideClass>slide2</slideClass>

    <button>
        <buttonClass>leftBottom</buttonClass>
        <to>3</to>
        <value>Vyjdu ze dveří.</value>
    </button>

    <button>
        <buttonClass>rightBottom</buttonClass>
        <to>1</to>
        <value>Vrátím se do postele.</value>
    </button>

    <text>
        <textClass>heading</textClass>
        <value>Tvůj nádherný dům. Má vše, co potřebuješ: dveře a postel. Co uděláš?</value>
    </text>

    <image>
        <imageClass>imageCenter</imageClass>
        <src>room.jpg</src>
    </image>

</slide>

<!-- slide 3 - Rozcestí -->
<slide>

    <slideClass>slide3</slideClass>

    <button>
        <buttonClass>left</buttonClass>
        <to>6</to>
        <value>Do školy.</value>
    </button>

    <button>
        <buttonClass>right</buttonClass>
        <to>4</to>
        <value>Do lesa.</value>
    </button>

    <button>
        <buttonClass>centerBottom</buttonClass>
        <to>2</to>
        <value>Domů.</value>
    </button>

    <text>
        <textClass>heading</textClass>
        <value>Vyšel jsi z domu a prašnou cestou jsi došel až na rozcestí. Kam se vydáš?</value>
    </text>

    <image>
        <imageClass>imageCenter</imageClass>
        <src>crossroad.png</src>
    </image>

</slide>

<!-- slide 4 - Les -->
<slide>

    <slideClass>slide4</slideClass>

    <button>
        <buttonClass>rightBottom</buttonClass>
        <to>3</to>
        <value>Vrátím se na rozcestí.</value>
    </button>

    <button>
        <buttonClass>leftBottom</buttonClass>
        <to>5</to>
        <value>Prozkoumám jeskyni.</value>
    </button>

    <text>
        <textClass>heading</textClass>
        <value>Došel jsi do lesa a našel jsi jeskyni. Co uděláš?</value>
    </text>

    <image>
        <imageClass>imageCenter</imageClass>
        <src>cave.jpg</src>
    </image>

    <audio>
        <audioClass>examle</audioClass>
        <src>forest.mp3</src>
        <loop/>
    </audio>

</slide>

<!-- slide 5 - medvěd -->
<slide>

    <slideClass>slide5</slideClass>

    <button>
        <buttonClass>leftBottom</buttonClass>
        <to>7</to>
        <value>Zaútočím na medvěda!</value>
    </button>

    <button>
        <buttonClass>rightBottom</buttonClass>
        <to>3</to>
        <value>Útěk!</value>
    </button>

    <text>
        <textClass>heading</textClass>
        <value>V téhle jeskyni někdo bydlí! Co teď?</value>
    </text>

    <image>
        <imageClass>imageCenter</imageClass>
        <src>bear.jpg</src>
    </image>

    <audio>
        <audioClass>examle</audioClass>
        <src>bear.mp3</src>
        <loop/>
    </audio>

</slide>

<!-- slide 6 - skola -->
<slide>
    <slideClass>slide6</slideClass>

    <text>
        <textClass>heading</textClass>
        <value>Došel jsi do školy a píše se test TINu, na který jsi se neučil. V otázka říká něco o množinách? Automaty? Jak odpovíš?</value>
    </text>

    <button>
        <buttonClass>right2</buttonClass>
        <to>7</to>
        <value>Budu rozmýšlet o další studium na FITu.</value>
    </button>

    <button>
        <buttonClass>right1</buttonClass>
        <to>7</to>
        <value>Nakreslím portrét Češky.</value>
    </button>

    <button>
        <buttonClass>right0</buttonClass>
        <to>7</to>
        <value>Nakreslím smajlíka.</value>
    </button>

    <button>
        <buttonClass>right3</buttonClass>
        <to>3</to>
        <value>Útěk!</value>
    </button>

    <image>
        <imageClass>imageLeft</imageClass>
        <src>exam.jpg</src>
    </image>

    <audio>
        <audioClass>examle</audioClass>
        <src>exam.mp3</src>
        <loop/>
    </audio>
</slide>

<!-- slide 7 - you died -->
<slide>

    <slideClass>slide7</slideClass>

    <button>
        <buttonClass>centerBottom</buttonClass>
        <to>0</to>
        <value>Restart</value>
    </button>

    <video>
        <videoClass>imageCenter</videoClass>
        <src>youdied.mp4</src>
    </video>

</slide>

</slides>
